#
# Configuration file for the AdminLTE bundle
#
# For more information about the bundle settings visit:
# https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/configurations.md
#
admin_lte:
    options:
        # default image for missing user avatar images
        default_avatar: bundles/adminlte/images/default_avatar.png
        # the color skin
        skin: skin-blue
        # if activated, the boxed_layout will be deactivated
        fixed_layout: false
        # boxed layout (true) or full-screen (false)
        boxed_layout: false
        # initial collapsed state of the sidebar
        collapsed_sidebar: false
        # whether the logo collapses or not
        mini_sidebar: false

    # configurable tabs in the control_sidebar (right screen), see:
    # https://github.com/kevinpapst/AdminLTEBundle/blob/master/Resources/docs/control_sidebar.md
    # control_sidebar:
    #    home:
    #        icon: fas fa-home
    #        template: control-sidebar/home.html.twig
    #    settings:
    #        icon: fas fa-cogs
    #        controller: 'App\Controller\DefaultController::controlSidebarSettings'


    theme:
        widget:
            type: 'primary'
            bordered: true
            collapsible: false
            collapsible_title: 'Collapse'
            removable: false
            removable_title: 'Remove'
            solid: false
            use_footer: true
        button:
            type: 'primary'
            size: false

    knp_menu:
        enable: false
        main_menu: adminlte_main
        breadcrumb_menu: false

    routes:
        adminlte_welcome: admin_dashboard
        adminlte_login: fos_user_security_login
        adminlte_login_check: fos_user_security_check
        adminlte_registration: fos_user_registration_register
        adminlte_password_reset: fos_user_resetting_request
        adminlte_message: homepage
        adminlte_messages: homepage
        adminlte_notification: homepage
        adminlte_notifications: homepage
        adminlte_task: homepage
        adminlte_tasks: homepage
        adminlte_profile: fos_user_profile_show


